
export QUESTA_HOME = c:/EDATools/Mentor/questasim64_10.6c
export UVM_HOME    = c:/EDATools/UVM/uvm-1.1d
#export UVM_HOME   = c:/EDATools/UVM/uvm-1.2

export PROJ_ROOT   = $(shell pwd)/../
export MODEL_HOME  = $(QUESTA_HOME)
export BITS        = 64
export UVM_VERSION = 1.1d

export FILE_LIST   = $(PROJ_ROOT)/filelist/apb_agent_tb.fl

include Makefile.questa
